name: Build Linux
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cmake libsdl2-dev
          cmake --version
      - name: Create build_GH directory
        run: |
          if mkdir -p /home/runner/work/Final-Project/Final-Project/build_GH; then
            echo "Directory created successfully!"
          else
            echo "Error Directory creation failed"
            exit 1
          fi
      - name: Build executable 
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          cmake ..
          make
      - name: Run hello_world tests
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          echo "Testing hello_world1.slug:"
          ./TheBanana ../hws/hello_world1.slug
          echo "Testing hello_world2.slug:"
          ./TheBanana ../hws/hello_world2.slug
          echo "Testing hello_world3.slug:"
          ./TheBanana ../hws/hello_world3.slug
