name: Build Linux
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cmake libsdl2-dev
          cmake --version
      - name: Create build_GH directory
        run: |
          if mkdir -p /home/runner/work/Final-Project/Final-Project/build_GH; then
            echo "Directory created successfully!"
          else
            echo "Error Directory creation failed"
            exit 1
          fi
      - name: Build executable 
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          cmake ..
          make

      - name: Convert line endings
        run: |
          sed -i 's/\r$//' tests/run_test.sh
        
      - name: Run hello_world1
        working-directory: /home/runner/work/Final-Project/Final-Project/tests
        run: |
          ./run_test.sh hello_world1 ./../build/TheBanana one.txt two.txt

      - name: Run hello_world2
        working-directory: /home/runner/work/Final-Project/Final-Project/tests
        run: |
          ./run_test.sh hello_world2 ./../build/TheBanana one.txt two.txt

      - name: Run hello_world3
        working-directory: /home/runner/work/Final-Project/Final-Project/tests
        run: |
          ./run_test.sh hello_world3 ./../build/TheBanana one.txt two.txt
