name: Build Linux
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cmake libsdl2-dev
          cmake --version
      - name: Create build_GH directory
        run: mkdir -p /home/runner/work/Final-Project/Final-Project/build_GH
      - name: Build executable 
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          cmake ..
          make
      - name: Run Executable
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          ./TheBanana ../hws/hello_world1.slug
