Skip to content
Navigation Menu
CSE111Group9
/
Final-Project

Type / to search

Code
Issues
Pull requests
1
Actions
Projects
Security
Insights
Settings
Build Linux
Update build.yml #160
Jobs
Run details
Workflow file for this run
.github/workflows/build.yml at 80f50fe
name: Build Linux
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cmake libsdl2-dev
          cmake --version
      - name: Create build_GH directory
        run: |
          if mkdir -p /home/runner/work/Final-Project/Final-Project/build_GH; then
            echo "Directory created successfully!"
          else
            echo "Error Directory creation failed"
            exit 1
          fi
      - name: Build executable 
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          cmake ..
          make
      - name: Run Executable
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          ./TheBanana ../hws/hello_world1.slug

      
      - name: Run hello_world2
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          ./TheBanana ../hws/hello_world2.slug
      
      - name: Run hello_world3
        working-directory: /home/runner/work/Final-Project/Final-Project/build_GH
        run: |
          ./TheBanana ../hws/hello_world3.slug
