name: Verify Formatting
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y clang-format
          clang-format --version
      - name: Run clang-format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -style=google -i 

      - name: Verify format
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Code is not formatted properly. Please run clang-format.";
            git diff; 
            exit 1;
          else
            echo "Code is properly formatted."; 
          fi
