name: Verify Formatting
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y clang-format
          sudo apt install -y cmake libsdl2-dev
          clang-format --version
      - name: Run clang-format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -style=google -i

      - name: Create build directory
        run: |
          if mkdir -p /home/runner/work/Final-Project/Final-Project/build; then
            echo "Directory created successfully!"
          else
            echo "Error Directory creation failed"
            exit 1
          fi
      - name: Build executable 
        working-directory: /home/runner/work/Final-Project/Final-Project/build
        run: |
          cmake ..
          make
